// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysrtpjnmrmzvrzbbypcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzcnRwam5tcm16dnJ6YmJ5cGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTIwOTgsImV4cCI6MjA2MzIyODA5OH0.eZwYSGAoSBh5WoYDjQHGNx3gH4p-goaK1hubIoY0-rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);